In [2]:
import pandas as pd
import sqlite3
from pathlib import Path

project_root = Path.cwd().parent
raw_data = project_root / "data" / "raw" / "customer_support_tickets.csv"
db = project_root / "data" / "processed" / "customer_support.db"

In [5]:
q1 = '''
SELECT ticket_id, ticket_channel, first_response_time
FROM tickets
WHERE ticket_channel = "Email"
ORDER BY first_response_time;
'''
with sqlite3.connect(db) as conn:
    result1 = pd.read_sql(q1, conn)

result1

      ticket_id ticket_channel  first_response_time
0            25          Email                  NaN
1            31          Email                  NaN
2            44          Email                  NaN
3            58          Email                  NaN
4            75          Email                  NaN
...         ...            ...                  ...
2138       7757          Email  2023-06-02 00:12:48
2139       7311          Email  2023-06-02 00:14:21
2140       7013          Email  2023-06-02 00:15:37
2141       8076          Email  2023-06-02 00:28:24
2142       8463          Email  2023-06-02 00:36:18

[2143 rows x 3 columns]

In [ ]:
q2 = '''
SELECT
    ticket_priority, COUNT(*) as count_for_priority, AVG(customer_satisfaction_rating) as avg_rating
FROM tickets 
GROUP BY ticket_priority
HAVING COUNT(*) > 500
'''

with sqlite3.connect(db) as conn:
    result2 = pd.read_sql(q2, conn)

result2

  ticket_priority  count_for_priority  acg_rating
0        Critical                2129    2.958678
1            High                2085    2.982979
2             Low                2063    3.052795
3          Medium                2192    2.976945